apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: abaad
data:
  my.cnf: |
    [mysqld]
    default-authentication-plugin=mysql_native_password
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_connections=200
    innodb_buffer_pool_size=512M
    innodb_log_file_size=128M
    slow_query_log=1
    long_query_time=2
